coins = {
	"Khan's Concentrated Magic": 80000,
	"Luminous Cobalt Ingot": 400,
	"Bright Reef Piece": 30,
	"Great Ocean Dark Iron": 130,
	"Cobalt Ingot": 120,
	"Brilliant Rock Salt Ingot": 400,
	"Seaweed Stalk": 80,
	"Enhanced Island Tree Coated Plywood": 40,
	"Pure Pearl Crystal": 200,
	"Cox Pirates' Artifact (Parley Beginner)": 120,
	"Cox Pirates' Artifact (Parley Expert)": 400,
	"Cox Pirates' Artifact (Combat)": 120,
	"Deep Sea Memory Filled Glue": 110,
	"Brilliant Pearl Shard": 400,
	"Ruddy Manganese Nodule": 200,
	"Tear of the Ocean": 400,
	"Khan's Tendon": 400,
	"Khan's Scale": 160,
	"Tidal Black Stone": 10,
	"Tide-Dyed Standardized Timber Square": 80,
	"Deep Tide-Dyed Standardized Timber Square": 80,
	"Moon Vein Flax Fabric": 40,
	"Moon Scale Plywood": 15,
	"Mandragora Essence": 100,
	"Glue With Traces of Deep Waves": 400,
}
