coins = {
	"Khan's Concentrated Magic": 80000,
	"Luminous Cobalt Ingot": 800,
	"Bright Reef Piece": 140,
	"Great Ocean Dark Iron": 160,
	"Cobalt Ingot": 150,
	"Brilliant Rock Salt Ingot": 1600,
	"Seaweed Stalk": 600,
	"Enhanced Island Tree Coated Plywood": 80,
	"Pure Pearl Crystal": 550,
	"Cox Pirates' Artifact (Parley Beginner)": 150,
	"Cox Pirates' Artifact (Parley Expert)": 800,
	"Cox Pirates' Artifact (Combat)": 800,
	"Deep Sea Memory Filled Glue": 140,
	"Brilliant Pearl Shard": 1600,
	"Ruddy Manganese Nodule": 1500,
	"Tear of the Ocean": 3900,
	"Khan's Tendon": 6000,
	"Khan's Scale": 1600,
	"Frosted Black Stone": 20,
	"Tide-Dyed Standardized Timber Square": 350,
	"Deep Tide-Dyed Standardized Timber Square": 1000,
	"Moon Vein Flax Fabric": 600,
	"Moon Scale Plywood": 160,
	"Fiery Black Stone": 10,
	"Mandragora Essence": 100,
}