coins = {
	"Khan's Concentrated Magic": 80000,
	"Luminous Cobalt Ingot": 500,
	"Bright Reef Piece": 40,
	"Great Ocean Dark Iron": 160,
	"Cobalt Ingot": 150,
	"Brilliant Rock Salt Ingot": 500,
	"Seaweed Stalk": 100,
	"Enhanced Island Tree Coated Plywood": 50,
	"Pure Pearl Crystal": 250,
	"Cox Pirates' Artifact (Parley Beginner)": 150,
	"Cox Pirates' Artifact (Parley Expert)": 500,
	"Cox Pirates' Artifact (Combat)": 150,
	"Deep Sea Memory Filled Glue": 140,
	"Brilliant Pearl Shard": 500,
	"Ruddy Manganese Nodule": 250,
	"Tear of the Ocean": 500,
	"Khan's Tendon": 500,
	"Khan's Scale": 200,
	"Tidal Black Stone": 10,
	"Tide-Dyed Standardized Timber Square": 100,
	"Deep Tide-Dyed Standardized Timber Square": 100,
	"Moon Vein Flax Fabric": 50,
	"Moon Scale Plywood": 20,
	"Mandragora Essence": 100,
}
