# a dictionary of barter item trade-ins

shipbarters = {
	"Bright Reef Piece": [{"count": "4", "input": ['[Level 3] Ancient Orders', '[Level 3] Lopters Fishnet', "[Level 3] Pirates' Supply Box", '[Level 3] Rare Herb Pile', '[Level 3] Scout Binoculars', '[Level 3] Skull Decorated Teacup', '[Level 3] Torn Pirate Treasure Map']}],
	"Brilliant Pearl Shard": [{"count": "1", "input": ['[Level 5] Elixir of Youth', '[Level 5] Mysterious Rock', '[Level 5] Octagonal Box']}],
	"Brilliant Rock Salt Ingot": [{"count": "1", "input": ['[Level 5] 102 Year Old Golden Herb', '[Level 5] Portrait of the Ancient', '[Level 5] Supreme Gold Candlestick', '[Level 5] Taxidermied Morpho Butterfly']}],
	"Cobalt Ingot": [{"count": "2", "input": ['[Level 2] Conch Shell Ornament', '[Level 2] Cron Castle Gold Coin', "[Level 2] Islanders' Lunchbox", '[Level 2] Narvo Sea Cucumber', '[Level 2] Opulent Marble', '[Level 2] Pirate Gold Coin', '[Level 2] Pirate Ship Mast', '[Level 2] Sea Survival Kit']}],
	"Cox Pirates Extermination Seal": [{"count": "#", "input": ['[Level 3] Ancient Orders', '[Level 3] Blue Candle Bundle', '[Level 3] Old Hourglass', "[Level 3] Pirates' Supply Box", '[Level 3] Rare Herb Pile', '[Level 3] Scout Binoculars', '[Level 3] Torn Pirate Treasure Map']}],
	"Cox Pirates' Artifact (Combat)": [{"count": "#", "input": ['[Level 5] 37 Year Old Herbal Wine', '[Level 5] Azure Quartz', '[Level 5] Faded Gold Dragon Figurine', '[Level 5] Golden Fish Scale', '[Level 5] Mysterious Rock', '[Level 5] Octagonal Box', "[Level 5] Statue's Tear", '[Level 5] Supreme Gold Candlestick', '[Level 5] Taxidermied Morpho Butterfly']}],
	"Cox Pirates' Artifact (Parley Beginner)": [{"count": "1", "input": ['[Level 2] Balanced Stone Pagoda', '[Level 2] Big Stone Slab', '[Level 2] Filtered Drinking Water', "[Level 2] Islanders' Lunchbox", '[Level 2] Opulent Marble', '[Level 2] Supreme Oyster Box', '[Level 2] Urchin Spine']}],
	"Cox Pirates' Artifact (Parley Expert)": [{"count": "1", "input": ['[Level 4] Bronze Candlestick', '[Level 4] Headless Dragon Figurine', '[Level 4] Old Chest with Gold Coins', '[Level 4] Opulent Thread Spool', '[Level 4] Solidified Lava']}],
	"Deep Sea Memory Filled Glue": [{"count": "4", "input": ['[Level 3] Blue Candle Bundle', '[Level 3] Old Hourglass', '[Level 3] Round Knife', '[Level 3] Skull Decorated Teacup', '[Level 3] Weasel Leather Coat']}],
	"Deep Tide-Dyed Standardized Timber Square": [{"count": "#", "input": ['[Level 5] 102 Year Old Golden Herb', '[Level 5] 37 Year Old Herbal Wine', '[Level 5] Azure Quartz', '[Level 5] Elixir of Youth', '[Level 5] Faded Gold Dragon Figurine', '[Level 5] Golden Fish Scale', '[Level 5] Luxury Patterned Fabric', '[Level 5] Mysterious Rock', '[Level 5] Octagonal Box', '[Level 5] Portrait of the Ancient', '[Level 5] Supreme Gold Candlestick', '[Level 5] Taxidermied Morpho Butterfly']}],
	"Enhanced Island Tree Coated Plywood": [{"count": "10", "input": ['[Level 4] Bronze Candlestick', '[Level 4] Green Salt Lump', '[Level 4] Headless Dragon Figurine', "[Level 4] Marine Knights' Spear", '[Level 4] Seashell Deco', '[Level 4] Stolen Pirate Dagger']}],
	"Great Ocean Dark Iron": [{"count": "5", "input": ['[Level 4] Amethyst Fragment', '[Level 4] Bronze Candlestick', '[Level 4] Opulent Thread Spool', '[Level 4] Panacea', "[Level 4] Pirate's Key", '[Level 4] Stolen Pirate Dagger']}],
	"Island Tree Coated Plywood": [{"count": "#", "input": ['Rock Salt Ingot']}, {"count": "100", "input": ['[Level 2] Filtered Drinking Water', "[Level 2] Islanders' Lunchbox", '[Level 2] Monster Tentacle', '[Level 2] Pirate Ship Mast', '[Level 2] Sea Survival Kit', '[Level 2] Supreme Oyster Box', '[Level 2] Urchin Spine']}],
	"Luminous Cobalt Ingot": [{"count": "1", "input": ['[Level 4] Old Chest with Gold Coins', '[Level 4] Solidified Lava']}],
	"Moon Scale Plywood": [{"count": "#", "input": ['[Level 5] Azure Quartz', '[Level 5] Elixir of Youth', '[Level 5] Faded Gold Dragon Figurine']}],
	"Moon Vein Flax Fabric": [{"count": "#", "input": ['[Level 5] 37 Year Old Herbal Wine', '[Level 5] Faded Gold Dragon Figurine', '[Level 5] Taxidermied White Caterpillar']}],
	"Pure Pearl Crystal": [{"count": "1", "input": ['[Level 3] Gooey Monster Blood', '[Level 3] Round Knife', '[Level 3] Skull Decorated Teacup', '[Level 3] Stalactite Fragment', '[Level 3] Weasel Leather Coat']}],
	"Rock Salt Ingot": [{"count": "#", "input": ['Island Tree Coated Plywood']}, {"count": "100", "input": ['[Level 2] Balanced Stone Pagoda', '[Level 2] Cron Castle Gold Coin', '[Level 2] Narvo Sea Cucumber', '[Level 2] Opulent Marble', '[Level 2] Sea Survival Kit', '[Level 2] Supreme Oyster Box']}],
	"Ruddy Manganese Nodule": [{"count": "#", "input": ['[Level 4] Amethyst Fragment', '[Level 4] Headless Dragon Figurine', "[Level 4] Marine Knights' Helm", '[Level 4] Opulent Thread Spool', "[Level 4] Pirate's Key", '[Level 4] Stolen Pirate Dagger']}],
	"Seaweed Stalk": [{"count": "#", "input": ["[Level 4] Boatman's Manual", '[Level 4] Green Salt Lump', "[Level 4] Marine Knights' Helm", "[Level 4] Marine Knights' Spear", '[Level 4] Panacea', "[Level 4] Pirate's Key"]}],
	"Tear of the Ocean": [{"count": "#", "input": ['[Level 5] 102 Year Old Golden Herb', '[Level 5] Azure Quartz', '[Level 5] Faded Gold Dragon Figurine', '[Level 5] Golden Fish Scale', '[Level 5] Portrait of the Ancient', "[Level 5] Statue's Tear", '[Level 5] Supreme Gold Candlestick', '[Level 5] Taxidermied Morpho Butterfly', '[Level 5] Taxidermied White Caterpillar']}],
	"Tide-Dyed Standardized Timber Square": [{"count": "#", "input": ['[Level 4] Amethyst Fragment', "[Level 4] Marine Knights' Helm", '[Level 4] Panacea']}]
}