# a dictionary of item notes

items = {
	"Bartali Sailboat": ["Buy from Proix. 10 mil"],
	"Epheria Sailboat": ["Buy on CM or craft from Bartali Sailboat", "Improved Sailboat works for Caravel"],
	"Epheria Frigate": ["Buy on CM or craft from Bartali Sailboat", "Improved Frigate works for Galleass"],
	"Epheria Caravel": ["Craft from Epheria Sailboat"],
	"Epheria Galleass": ["Craft from Epheria Frigate"],
	"Ship Upgrade Permit: Epheria Sailboat": ["Buy from Falasi. 100 mil."],
	"Ship Upgrade Permit: Epheria Frigate": ["Buy from Falasi. 200 mil."],
	"Ship Upgrade Permit: Epheria Caravel": ["Buy from Falasi. 400 mil."],
	"Ship Upgrade Permit: Epheria Galleass": ["Buy from Falasi. 600 mil."],
	"Verdant Black Stone": ["100 total from Ravinia's quest rewards day 1&4", "5 per completion of the Great Sea MSQ", "Rare sea monster drop"],
	"Ultimate Armor Reform Stone": ["Buy from CM"],
	"Ultimate Weapon Reform Stone": ["Buy from CM"],
	"Black Stone (Armor)": ["Buy from CM"],

	"Bartali Sailboat: Old Prow": ["Buy from Falasi. 400k."],
	"Bartali Sailboat: Old Plating": ["Buy from Falasi. 500k."],
	"Bartali Sailboat: Old Cannon": ["Buy from Falasi. 400k."],
	"Bartali Sailboat: Old Sail": ["Buy from Falasi. 300k."],

	"Epheria: Old Prow": ["Buy from Falasi. 3.5 mil."],
	"Epheria: Old Plating": ["Buy from Falasi. 4 mil."],
	"Epheria: Old Cannon": ["Buy from Falasi. 3.5 mil."],
	"Epheria: Old Sail": ["Buy from Falasi. 3 mil."],

	"Epheria Caravel: Brass Prow": ["Buy from Falasi. 8 mil."],
	"Epheria Caravel: Upgraded Plating (Green)": ["Buy from Falasi. 9 mil."],
	"Epheria Caravel: Verisha Cannon": ["Buy from Falasi. 8 mil."],
	"Epheria Caravel: White Wind Sail": ["Buy from Falasi. 7 mil."],

	"Epheria Galleass: White Horn Prow": ["Buy from Falasi. 8 mil."],
	"Epheria Galleass: Upgraded Plating (Green)": ["Buy from Falasi. 9 mil."],
	"Epheria Galleass: Verisha Cannon": ["Buy from Falasi. 8 mil."],
	"Epheria Galleass: White Wind Sail": ["Buy from Falasi. 7 mil."],

	"Epheria Caravel: Black Dragon Prow": ["Make at Epheria Ship Parts Shop"],
	"Epheria Caravel: Upgraded Plating (Blue)": ["Make at Epheria Ship Parts Shop"],
	"Epheria Caravel: Mayna Cannon": ["Make at Epheria Ship Parts Shop"],
	"Epheria Caravel: Stratus Wind Sail": ["Make at Epheria Ship Parts Shop"],

	"Epheria Galleass: Black Dragon Prow": ["Make at Epheria Ship Parts Shop"],
	"Epheria Galleass: Upgraded Plating (Blue)": ["Make at Epheria Ship Parts Shop"],
	"Epheria Galleass: Mayna Cannon": ["Make at Epheria Ship Parts Shop"],
	"Epheria Galleass: Stratus Wind Sail": ["Make at Epheria Ship Parts Shop"],

	"Sea Monster's Ooze": ["Hungry Heraku or Hungry Ocean Stalker drop", "Recipe item for Graphite Ingot for Upgrade", "Recipe item for Timber for Upgrade", "Recipe item for Adhesive for Upgrade"],
	"Graphite Ingot for Upgrade": ["1x per Heating", "50 total from Ravinia's quest rewards day 1&4"],
	"Timber for Upgrade": ["1x per Chopping", "50 total from Ravinia's quest rewards day 1&4"],
	"Adhesive for Upgrade": ["1x per Heating", "50 total from Ravinia's quest rewards day 1&4"],

	"Zinc Ingot": ["Buy from CM or process", "Recipe item for Graphite Ingot for Upgrade"],
	"Old Tree Bark": ["Buy from CM or gather with workers", "Recipe item for Timber for Upgrade"],
	"Red Tree Lump": ["Buy from CM or gather with workers", "Recipe item for Timber for Upgrade"],
	"White Cedar Sap": ["Buy from CM or gather with workers", "Recipe item for Adhesive for Upgrade"],
	"Acacia Sap": ["Buy from CM or gather with workers", "Recipe item for Adhesive for Upgrade"],
	"Elder Tree Sap": ["Buy from CM or gather with workers", "Recipe item for Adhesive for Upgrade"],

	"Standardized Timber Square": ["Buy from CM or process"],
	"Steel": ["Buy from CM or process"],
	"Pine Plywood": ["Buy from CM or process"],
	"Flax Fabric": ["Buy from CM or process"],
	"Hard Pillar": ["Buy from CM or process"],
	"Jade Coral Ingot": ["Buy from CM or process"],
	"Pine Coated Plywood": ["Buy from CM or process"],
	"Enhanced Flax Fabric": ["Buy from CM or process"],

#	"Khan's Concentrated Magic": [],
#	"Luminous Cobalt Ingot": [],
	"Bright Reef Piece": ["8x per [Daily] Ravikel's Test"],
#	"Great Ocean Dark Iron": [],
	"Cobalt Ingot": ["Rare sea monster drop"],
	"Brilliant Rock Salt Ingot": ["Black Rust Sea Monster"],
	"Seaweed Stalk": ["4x per [Daily] Precious Coral Piece", "Suspicious Cargo Ship"],
	"Enhanced Island Tree Coated Plywood": ["10x per [Daily] For the Serendian Soldiers"],
	"Pure Pearl Crystal": ["2x per [Daily] Ravikel's Test"],
#	"Cox Pirates' Artifact (Parley Beginner)": [],
	"Cox Pirates' Artifact (Parley Expert)": ["1x per [Daily] For the Serendian Soldiers"],
	"Cox Pirates' Artifact (Combat)": ["3x per [Daily] Do You Have What it Takes?", "Cox Pirates' Shadow Ghost drop", "Cox Pirate Extermination Seal X200"],
	"Deep Sea Memory Filled Glue": ["8x per [Daily] Ravikel's Test", "Young Ocean Stalker rare drop"],
#	"Brilliant Pearl Shard": [],
	"Ruddy Manganese Nodule": ["2x per [Daily] For the Young Otter Merchants", "Suspicious Cargo Ship"],
	"Tear of the Ocean": ["1x per [Daily] OMG's Black Rust Hunter", "0.5x per [Daily] OMG's Young Black Rust Hunter"],
#	"Khan's Tendon": [],
#	"Khan's Scale": [],
#	"Frosted Black Stone": [],
	"Tide-Dyed Standardized Timber Square": ["3x per [Daily] Our Guild is not a Charity Group", "Cox Pirates' Shadow Ghost drop"],
	"Deep Tide-Dyed Standardized Timber Square": ["3x per [Daily] Win-win Situation", "Cox Pirates' Shadow Ghost rare drop"],
	"Moon Vein Flax Fabric": ["3x per [Daily] OMG's Nineshark Hunter", "1x per [Daily] OMG's Young Nineshark Hunter", "10x from drying Khan's Tendon"],
	"Moon Scale Plywood": ["10x per [Daily] OMG's Candidum Hunter", "5x per [Daily] OMG's Young Candidum Hunter", "10x from drying Khan's Scale"],
#	"Fiery Black Stone": [],
#	"Mandragora Essence": [],
}