# A recipe dictionary

recipes = {
	# Ships
	"Epheria Sailboat": {
		"Bartali Sailboat": 1,
		"Ship Upgrade Permit: Epheria Sailboat": 1,
		"+10 Bartali Sailboat: Old Prow": 1,
		"+10 Bartali Sailboat: Old Plating": 1,
		"+10 Bartali Sailboat: Old Cannon": 1,
		"+10 Bartali Sailboat: Old Sail": 1,
		"Standardized Timber Square": 800,
		"Steel": 600,
		"Pine Plywood": 1500,
		"Flax Fabric": 300,
		"Hard Pillar": 100,
	},
	"Improved Epheria Sailboat": {
		"Epheria Sailboat": 1,
		"Bartali Sailboat: Old Prow": 1,
		"Bartali Sailboat: Old Plating": 1,
		"Bartali Sailboat: Old Cannon": 1,
		"Bartali Sailboat: Old Sail": 1,
		"Standardized Timber Square": 250,
		"Steel": 200,
		"Pine Plywood": 500,
		"Flax Fabric": 100,
		"Hard Pillar": 30,
		"Ultimate Armor Reform Stone": 10
	},
	"Epheria Caravel": {
		"Epheria Sailboat": 1,
		"Ship Upgrade Permit: Epheria Caravel": 1,
		"+10 Epheria: Old Prow": 1,
		"+10 Epheria: Old Plating": 1,
		"+10 Epheria: Old Cannon": 1,
		"+10 Epheria: Old Sail": 1,
		"Graphite Ingot for Upgrade": 100,
		"Timber for Upgrade": 100,
		"Adhesive for Upgrade": 100,
		"Island Tree Coated Plywood": 100,
		"Rock Salt Ingot": 100,
		"Deep Sea Memory Filled Glue": 4,
		"Seaweed Stalk": 6
	},
	"Carrack (Advance)": {},
	"Carrack (Balance)": {},
	"Epheria Frigate": {
		"Bartali Sailboat": 1,
		"+10 Bartali Sailboat: Old Prow": 1,
		"+10 Bartali Sailboat: Old Plating": 1,
		"+10 Bartali Sailboat: Old Cannon": 1,
		"+10 Bartali Sailboat: Old Sail": 1,
		"Standardized Timber Square": 1000,
		"Jade Coral Ingot": 600,
		"Pine Coated Plywood": 1500,
		"Enhanced Flax Fabric": 300,
		"Hard Pillar": 100,

	},
	"Improved Epheria Frigate": {
		"Epheria Frigate": 1,
		"Bartali Sailboat: Old Prow": 1,
		"Bartali Sailboat: Old Plating": 1,
		"Bartali Sailboat: Old Cannon": 1,
		"Bartali Sailboat: Old Sail": 1,
		"Standardized Timber Square": 250,
		"Steel": 200,
		"Pine Plywood": 500,
		"Flax Fabric": 100,
		"Hard Pillar": 30,
		"Ultimate Weapon Reform Stone": 10
	},
	"Epheria Gaileass": {
		"Epheria Frigate": 1,
		"Ship Upgrade Permit: Epheria Galleass": 1,
		"+10 Epheria: Old Prow": 1,
		"+10 Epheria: Old Plating": 1,
		"+10 Epheria: Old Cannon": 1,
		"+10 Epheria: Old Sail": 1,
		"Graphite Ingot for Upgrade": 100,
		"Timber for Upgrade": 100,
		"Adhesive for Upgrade": 100,
		"Island Tree Coated Plywood": 100,
		"Tide-Dyed Standardized Timber Square": 6,
		"Cobalt Ingot": 2,
		"Moon Scale Plywood": 10
	},
	"Carrack (Volante)": {},
	"Carrack (Valor)": {},

	# Upgrade parts
	"Graphite Ingot for Upgrade": {"Zinc Ingot": 100, "Sea Monster's Ooze": 1},
	"Timber for Upgrade": {"Old Tree Bark": 100, "Red Tree Lump": 100, "Sea Monster's Ooze": 1},
	"Adhesive for Upgrade": {"White Cedar Sap": 100, "Acacia Sap": 100, "Elder Tree Sap": 100, "Sea Monster's Ooze": 1},

	# Gear (used for upgrading ship to next type)
	"+10 Bartali Sailboat: Old Prow": {"+9 Bartali Sailboat: Old Prow": 1, "Black Stone (Armor)": 10},
	"+9 Bartali Sailboat: Old Prow": {"+8 Bartali Sailboat: Old Prow": 1, "Black Stone (Armor)": 9},
	"+8 Bartali Sailboat: Old Prow": {"+7 Bartali Sailboat: Old Prow": 1, "Black Stone (Armor)": 8},
	"+7 Bartali Sailboat: Old Prow": {"+6 Bartali Sailboat: Old Prow": 1, "Black Stone (Armor)": 7},
	"+6 Bartali Sailboat: Old Prow": {"+5 Bartali Sailboat: Old Prow": 1, "Black Stone (Armor)": 6},
	"+5 Bartali Sailboat: Old Prow": {"+4 Bartali Sailboat: Old Prow": 1, "Black Stone (Armor)": 5},
	"+4 Bartali Sailboat: Old Prow": {"+3 Bartali Sailboat: Old Prow": 1, "Black Stone (Armor)": 4},
	"+3 Bartali Sailboat: Old Prow": {"+2 Bartali Sailboat: Old Prow": 1, "Black Stone (Armor)": 3},
	"+2 Bartali Sailboat: Old Prow": {"+1 Bartali Sailboat: Old Prow": 1, "Black Stone (Armor)": 2},
	"+1 Bartali Sailboat: Old Prow": {"Bartali Sailboat: Old Prow": 1, "Black Stone (Armor)": 1},
	"+10 Bartali Sailboat: Old Plating": {"+9 Bartali Sailboat: Old Plating": 1, "Black Stone (Armor)": 10},
	"+9 Bartali Sailboat: Old Plating": {"+8 Bartali Sailboat: Old Plating": 1, "Black Stone (Armor)": 9},
	"+8 Bartali Sailboat: Old Plating": {"+7 Bartali Sailboat: Old Plating": 1, "Black Stone (Armor)": 8},
	"+7 Bartali Sailboat: Old Plating": {"+6 Bartali Sailboat: Old Plating": 1, "Black Stone (Armor)": 7},
	"+6 Bartali Sailboat: Old Plating": {"+5 Bartali Sailboat: Old Plating": 1, "Black Stone (Armor)": 6},
	"+5 Bartali Sailboat: Old Plating": {"+4 Bartali Sailboat: Old Plating": 1, "Black Stone (Armor)": 5},
	"+4 Bartali Sailboat: Old Plating": {"+3 Bartali Sailboat: Old Plating": 1, "Black Stone (Armor)": 4},
	"+3 Bartali Sailboat: Old Plating": {"+2 Bartali Sailboat: Old Plating": 1, "Black Stone (Armor)": 3},
	"+2 Bartali Sailboat: Old Plating": {"+1 Bartali Sailboat: Old Plating": 1, "Black Stone (Armor)": 2},
	"+1 Bartali Sailboat: Old Plating": {"Bartali Sailboat: Old Plating": 1, "Black Stone (Armor)": 1},
	"+10 Bartali Sailboat: Old Cannon": {"+9 Bartali Sailboat: Old Cannon": 1, "Black Stone (Armor)": 10},
	"+9 Bartali Sailboat: Old Cannon": {"+8 Bartali Sailboat: Old Cannon": 1, "Black Stone (Armor)": 9},
	"+8 Bartali Sailboat: Old Cannon": {"+7 Bartali Sailboat: Old Cannon": 1, "Black Stone (Armor)": 8},
	"+7 Bartali Sailboat: Old Cannon": {"+6 Bartali Sailboat: Old Cannon": 1, "Black Stone (Armor)": 7},
	"+6 Bartali Sailboat: Old Cannon": {"+5 Bartali Sailboat: Old Cannon": 1, "Black Stone (Armor)": 6},
	"+5 Bartali Sailboat: Old Cannon": {"+4 Bartali Sailboat: Old Cannon": 1, "Black Stone (Armor)": 5},
	"+4 Bartali Sailboat: Old Cannon": {"+3 Bartali Sailboat: Old Cannon": 1, "Black Stone (Armor)": 4},
	"+3 Bartali Sailboat: Old Cannon": {"+2 Bartali Sailboat: Old Cannon": 1, "Black Stone (Armor)": 3},
	"+2 Bartali Sailboat: Old Cannon": {"+1 Bartali Sailboat: Old Cannon": 1, "Black Stone (Armor)": 2},
	"+1 Bartali Sailboat: Old Cannon": {"Bartali Sailboat: Old Cannon": 1, "Black Stone (Armor)": 1},
	"+10 Bartali Sailboat: Old Sail": {"+9 Bartali Sailboat: Old Sail": 1, "Black Stone (Armor)": 10},
	"+9 Bartali Sailboat: Old Sail": {"+8 Bartali Sailboat: Old Sail": 1, "Black Stone (Armor)": 9},
	"+8 Bartali Sailboat: Old Sail": {"+7 Bartali Sailboat: Old Sail": 1, "Black Stone (Armor)": 8},
	"+7 Bartali Sailboat: Old Sail": {"+6 Bartali Sailboat: Old Sail": 1, "Black Stone (Armor)": 7},
	"+6 Bartali Sailboat: Old Sail": {"+5 Bartali Sailboat: Old Sail": 1, "Black Stone (Armor)": 6},
	"+5 Bartali Sailboat: Old Sail": {"+4 Bartali Sailboat: Old Sail": 1, "Black Stone (Armor)": 5},
	"+4 Bartali Sailboat: Old Sail": {"+3 Bartali Sailboat: Old Sail": 1, "Black Stone (Armor)": 4},
	"+3 Bartali Sailboat: Old Sail": {"+2 Bartali Sailboat: Old Sail": 1, "Black Stone (Armor)": 3},
	"+2 Bartali Sailboat: Old Sail": {"+1 Bartali Sailboat: Old Sail": 1, "Black Stone (Armor)": 2},
	"+1 Bartali Sailboat: Old Sail": {"Bartali Sailboat: Old Sail": 1, "Black Stone (Armor)": 1},

	"+10 Epheria: Old Prow": {"+9 Epheria: Old Prow": 1, "Verdant Black Stones": 10},
	"+9 Epheria: Old Prow": {"+8 Epheria: Old Prow": 1, "Verdant Black Stones": 9},
	"+8 Epheria: Old Prow": {"+7 Epheria: Old Prow": 1, "Verdant Black Stones": 8},
	"+7 Epheria: Old Prow": {"+6 Epheria: Old Prow": 1, "Verdant Black Stones": 7},
	"+6 Epheria: Old Prow": {"+5 Epheria: Old Prow": 1, "Verdant Black Stones": 6},
	"+5 Epheria: Old Prow": {"+4 Epheria: Old Prow": 1, "Verdant Black Stones": 5},
	"+4 Epheria: Old Prow": {"+3 Epheria: Old Prow": 1, "Verdant Black Stones": 4},
	"+3 Epheria: Old Prow": {"+2 Epheria: Old Prow": 1, "Verdant Black Stones": 3},
	"+2 Epheria: Old Prow": {"+1 Epheria: Old Prow": 1, "Verdant Black Stones": 2},
	"+1 Epheria: Old Prow": {"Epheria: Old Prow": 1, "Verdant Black Stones": 1},
	"+10 Epheria: Old Plating": {"+9 Epheria: Old Plating": 1, "Verdant Black Stones": 10},
	"+9 Epheria: Old Plating": {"+8 Epheria: Old Plating": 1, "Verdant Black Stones": 9},
	"+8 Epheria: Old Plating": {"+7 Epheria: Old Plating": 1, "Verdant Black Stones": 8},
	"+7 Epheria: Old Plating": {"+6 Epheria: Old Plating": 1, "Verdant Black Stones": 7},
	"+6 Epheria: Old Plating": {"+5 Epheria: Old Plating": 1, "Verdant Black Stones": 6},
	"+5 Epheria: Old Plating": {"+4 Epheria: Old Plating": 1, "Verdant Black Stones": 5},
	"+4 Epheria: Old Plating": {"+3 Epheria: Old Plating": 1, "Verdant Black Stones": 4},
	"+3 Epheria: Old Plating": {"+2 Epheria: Old Plating": 1, "Verdant Black Stones": 3},
	"+2 Epheria: Old Plating": {"+1 Epheria: Old Plating": 1, "Verdant Black Stones": 2},
	"+1 Epheria: Old Plating": {"Epheria: Old Plating": 1, "Verdant Black Stones": 1},
	"+10 Epheria: Old Cannon": {"+9 Epheria: Old Cannon": 1, "Verdant Black Stones": 10},
	"+9 Epheria: Old Cannon": {"+8 Epheria: Old Cannon": 1, "Verdant Black Stones": 9},
	"+8 Epheria: Old Cannon": {"+7 Epheria: Old Cannon": 1, "Verdant Black Stones": 8},
	"+7 Epheria: Old Cannon": {"+6 Epheria: Old Cannon": 1, "Verdant Black Stones": 7},
	"+6 Epheria: Old Cannon": {"+5 Epheria: Old Cannon": 1, "Verdant Black Stones": 6},
	"+5 Epheria: Old Cannon": {"+4 Epheria: Old Cannon": 1, "Verdant Black Stones": 5},
	"+4 Epheria: Old Cannon": {"+3 Epheria: Old Cannon": 1, "Verdant Black Stones": 4},
	"+3 Epheria: Old Cannon": {"+2 Epheria: Old Cannon": 1, "Verdant Black Stones": 3},
	"+2 Epheria: Old Cannon": {"+1 Epheria: Old Cannon": 1, "Verdant Black Stones": 2},
	"+1 Epheria: Old Cannon": {"Epheria: Old Cannon": 1, "Verdant Black Stones": 1},
	"+10 Epheria: Old Sail": {"+9 Epheria: Old Sail": 1, "Verdant Black Stones": 10},
	"+9 Epheria: Old Sail": {"+8 Epheria: Old Sail": 1, "Verdant Black Stones": 9},
	"+8 Epheria: Old Sail": {"+7 Epheria: Old Sail": 1, "Verdant Black Stones": 8},
	"+7 Epheria: Old Sail": {"+6 Epheria: Old Sail": 1, "Verdant Black Stones": 7},
	"+6 Epheria: Old Sail": {"+5 Epheria: Old Sail": 1, "Verdant Black Stones": 6},
	"+5 Epheria: Old Sail": {"+4 Epheria: Old Sail": 1, "Verdant Black Stones": 5},
	"+4 Epheria: Old Sail": {"+3 Epheria: Old Sail": 1, "Verdant Black Stones": 4},
	"+3 Epheria: Old Sail": {"+2 Epheria: Old Sail": 1, "Verdant Black Stones": 3},
	"+2 Epheria: Old Sail": {"+1 Epheria: Old Sail": 1, "Verdant Black Stones": 2},
	"+1 Epheria: Old Sail": {"Epheria: Old Sail": 1, "Verdant Black Stones": 1},

	"+10 Epheria Caravel: Brass Prow": {"+9 Epheria Caravel: Brass Prow": 1, "Frosted Black Stone": 1},
	"+9 Epheria Caravel: Brass Prow": {"+8 Epheria Caravel: Brass Prow": 1, "Frosted Black Stone": 1},
	"+8 Epheria Caravel: Brass Prow": {"+7 Epheria Caravel: Brass Prow": 1, "Frosted Black Stone": 1},
	"+7 Epheria Caravel: Brass Prow": {"+6 Epheria Caravel: Brass Prow": 1, "Frosted Black Stone": 1},
	"+6 Epheria Caravel: Brass Prow": {"+5 Epheria Caravel: Brass Prow": 1, "Frosted Black Stone": 1},
	"+5 Epheria Caravel: Brass Prow": {"+4 Epheria Caravel: Brass Prow": 1, "Fiery Black Stone": 1},
	"+4 Epheria Caravel: Brass Prow": {"+3 Epheria Caravel: Brass Prow": 1, "Fiery Black Stone": 1},
	"+3 Epheria Caravel: Brass Prow": {"+2 Epheria Caravel: Brass Prow": 1, "Fiery Black Stone": 1},
	"+2 Epheria Caravel: Brass Prow": {"+1 Epheria Caravel: Brass Prow": 1, "Fiery Black Stone": 1},
	"+1 Epheria Caravel: Brass Prow": {"Epheria Caravel: Brass Prow": 1, "Fiery Black Stone": 1},
	"+10 Epheria Caravel: Upgraded Plating (Green)": {"+9 Epheria Caravel: Upgraded Plating (Green)": 1, "Frosted Black Stone": 1},
	"+9 Epheria Caravel: Upgraded Plating (Green)": {"+8 Epheria Caravel: Upgraded Plating (Green)": 1, "Frosted Black Stone": 1},
	"+8 Epheria Caravel: Upgraded Plating (Green)": {"+7 Epheria Caravel: Upgraded Plating (Green)": 1, "Frosted Black Stone": 1},
	"+7 Epheria Caravel: Upgraded Plating (Green)": {"+6 Epheria Caravel: Upgraded Plating (Green)": 1, "Frosted Black Stone": 1},
	"+6 Epheria Caravel: Upgraded Plating (Green)": {"+5 Epheria Caravel: Upgraded Plating (Green)": 1, "Frosted Black Stone": 1},
	"+5 Epheria Caravel: Upgraded Plating (Green)": {"+4 Epheria Caravel: Upgraded Plating (Green)": 1, "Fiery Black Stone": 1},
	"+4 Epheria Caravel: Upgraded Plating (Green)": {"+3 Epheria Caravel: Upgraded Plating (Green)": 1, "Fiery Black Stone": 1},
	"+3 Epheria Caravel: Upgraded Plating (Green)": {"+2 Epheria Caravel: Upgraded Plating (Green)": 1, "Fiery Black Stone": 1},
	"+2 Epheria Caravel: Upgraded Plating (Green)": {"+1 Epheria Caravel: Upgraded Plating (Green)": 1, "Fiery Black Stone": 1},
	"+1 Epheria Caravel: Upgraded Plating (Green)": {"Epheria Caravel: Upgraded Plating (Green)": 1, "Fiery Black Stone": 1},
	"+10 Epheria Caravel: Verisha Cannon": {"+9 Epheria Caravel: Verisha Cannon": 1, "Frosted Black Stone": 1},
	"+9 Epheria Caravel: Verisha Cannon": {"+8 Epheria Caravel: Verisha Cannon": 1, "Frosted Black Stone": 1},
	"+8 Epheria Caravel: Verisha Cannon": {"+7 Epheria Caravel: Verisha Cannon": 1, "Frosted Black Stone": 1},
	"+7 Epheria Caravel: Verisha Cannon": {"+6 Epheria Caravel: Verisha Cannon": 1, "Frosted Black Stone": 1},
	"+6 Epheria Caravel: Verisha Cannon": {"+5 Epheria Caravel: Verisha Cannon": 1, "Frosted Black Stone": 1},
	"+5 Epheria Caravel: Verisha Cannon": {"+4 Epheria Caravel: Verisha Cannon": 1, "Fiery Black Stone": 1},
	"+4 Epheria Caravel: Verisha Cannon": {"+3 Epheria Caravel: Verisha Cannon": 1, "Fiery Black Stone": 1},
	"+3 Epheria Caravel: Verisha Cannon": {"+2 Epheria Caravel: Verisha Cannon": 1, "Fiery Black Stone": 1},
	"+2 Epheria Caravel: Verisha Cannon": {"+1 Epheria Caravel: Verisha Cannon": 1, "Fiery Black Stone": 1},
	"+1 Epheria Caravel: Verisha Cannon": {"Epheria Caravel: Verisha Cannon": 1, "Fiery Black Stone": 1},
	"+10 Epheria Caravel: White Wind Sail": {"+9 Epheria Caravel: White Wind Sail": 1, "Frosted Black Stone": 1},
	"+9 Epheria Caravel: White Wind Sail": {"+8 Epheria Caravel: White Wind Sail": 1, "Frosted Black Stone": 1},
	"+8 Epheria Caravel: White Wind Sail": {"+7 Epheria Caravel: White Wind Sail": 1, "Frosted Black Stone": 1},
	"+7 Epheria Caravel: White Wind Sail": {"+6 Epheria Caravel: White Wind Sail": 1, "Frosted Black Stone": 1},
	"+6 Epheria Caravel: White Wind Sail": {"+5 Epheria Caravel: White Wind Sail": 1, "Frosted Black Stone": 1},
	"+5 Epheria Caravel: White Wind Sail": {"+4 Epheria Caravel: White Wind Sail": 1, "Fiery Black Stone": 1},
	"+4 Epheria Caravel: White Wind Sail": {"+3 Epheria Caravel: White Wind Sail": 1, "Fiery Black Stone": 1},
	"+3 Epheria Caravel: White Wind Sail": {"+2 Epheria Caravel: White Wind Sail": 1, "Fiery Black Stone": 1},
	"+2 Epheria Caravel: White Wind Sail": {"+1 Epheria Caravel: White Wind Sail": 1, "Fiery Black Stone": 1},
	"+1 Epheria Caravel: White Wind Sail": {"Epheria Caravel: White Wind Sail": 1, "Fiery Black Stone": 1},

	"+10 Epheria Galleass: White Horn Prow": {"+9 Epheria Galleass: White Horn Prow": 1, "Frosted Black Stone": 1},
	"+9 Epheria Galleass: White Horn Prow": {"+8 Epheria Galleass: White Horn Prow": 1, "Frosted Black Stone": 1},
	"+8 Epheria Galleass: White Horn Prow": {"+7 Epheria Galleass: White Horn Prow": 1, "Frosted Black Stone": 1},
	"+7 Epheria Galleass: White Horn Prow": {"+6 Epheria Galleass: White Horn Prow": 1, "Frosted Black Stone": 1},
	"+6 Epheria Galleass: White Horn Prow": {"+5 Epheria Galleass: White Horn Prow": 1, "Frosted Black Stone": 1},
	"+5 Epheria Galleass: White Horn Prow": {"+4 Epheria Galleass: White Horn Prow": 1, "Fiery Black Stone": 1},
	"+4 Epheria Galleass: White Horn Prow": {"+3 Epheria Galleass: White Horn Prow": 1, "Fiery Black Stone": 1},
	"+3 Epheria Galleass: White Horn Prow": {"+2 Epheria Galleass: White Horn Prow": 1, "Fiery Black Stone": 1},
	"+2 Epheria Galleass: White Horn Prow": {"+1 Epheria Galleass: White Horn Prow": 1, "Fiery Black Stone": 1},
	"+1 Epheria Galleass: White Horn Prow": {"Epheria Galleass: White Horn Prow": 1, "Fiery Black Stone": 1},
	"+10 Epheria Galleass: Upgraded Plating (Green)": {"+9 Epheria Galleass: Upgraded Plating (Green)": 1, "Frosted Black Stone": 1},
	"+9 Epheria Galleass: Upgraded Plating (Green)": {"+8 Epheria Galleass: Upgraded Plating (Green)": 1, "Frosted Black Stone": 1},
	"+8 Epheria Galleass: Upgraded Plating (Green)": {"+7 Epheria Galleass: Upgraded Plating (Green)": 1, "Frosted Black Stone": 1},
	"+7 Epheria Galleass: Upgraded Plating (Green)": {"+6 Epheria Galleass: Upgraded Plating (Green)": 1, "Frosted Black Stone": 1},
	"+6 Epheria Galleass: Upgraded Plating (Green)": {"+5 Epheria Galleass: Upgraded Plating (Green)": 1, "Frosted Black Stone": 1},
	"+5 Epheria Galleass: Upgraded Plating (Green)": {"+4 Epheria Galleass: Upgraded Plating (Green)": 1, "Fiery Black Stone": 1},
	"+4 Epheria Galleass: Upgraded Plating (Green)": {"+3 Epheria Galleass: Upgraded Plating (Green)": 1, "Fiery Black Stone": 1},
	"+3 Epheria Galleass: Upgraded Plating (Green)": {"+2 Epheria Galleass: Upgraded Plating (Green)": 1, "Fiery Black Stone": 1},
	"+2 Epheria Galleass: Upgraded Plating (Green)": {"+1 Epheria Galleass: Upgraded Plating (Green)": 1, "Fiery Black Stone": 1},
	"+1 Epheria Galleass: Upgraded Plating (Green)": {"Epheria Galleass: Upgraded Plating (Green)": 1, "Fiery Black Stone": 1},
	"+10 Epheria Galleass: Verisha Cannon": {"+9 Epheria Galleass: Verisha Cannon": 1, "Frosted Black Stone": 1},
	"+9 Epheria Galleass: Verisha Cannon": {"+8 Epheria Galleass: Verisha Cannon": 1, "Frosted Black Stone": 1},
	"+8 Epheria Galleass: Verisha Cannon": {"+7 Epheria Galleass: Verisha Cannon": 1, "Frosted Black Stone": 1},
	"+7 Epheria Galleass: Verisha Cannon": {"+6 Epheria Galleass: Verisha Cannon": 1, "Frosted Black Stone": 1},
	"+6 Epheria Galleass: Verisha Cannon": {"+5 Epheria Galleass: Verisha Cannon": 1, "Frosted Black Stone": 1},
	"+5 Epheria Galleass: Verisha Cannon": {"+4 Epheria Galleass: Verisha Cannon": 1, "Fiery Black Stone": 1},
	"+4 Epheria Galleass: Verisha Cannon": {"+3 Epheria Galleass: Verisha Cannon": 1, "Fiery Black Stone": 1},
	"+3 Epheria Galleass: Verisha Cannon": {"+2 Epheria Galleass: Verisha Cannon": 1, "Fiery Black Stone": 1},
	"+2 Epheria Galleass: Verisha Cannon": {"+1 Epheria Galleass: Verisha Cannon": 1, "Fiery Black Stone": 1},
	"+1 Epheria Galleass: Verisha Cannon": {"Epheria Galleass: Verisha Cannon": 1, "Fiery Black Stone": 1},
	"+10 Epheria Galleass: White Wind Sail": {"+9 Epheria Galleass: White Wind Sail": 1, "Frosted Black Stone": 1},
	"+9 Epheria Galleass: White Wind Sail": {"+8 Epheria Galleass: White Wind Sail": 1, "Frosted Black Stone": 1},
	"+8 Epheria Galleass: White Wind Sail": {"+7 Epheria Galleass: White Wind Sail": 1, "Frosted Black Stone": 1},
	"+7 Epheria Galleass: White Wind Sail": {"+6 Epheria Galleass: White Wind Sail": 1, "Frosted Black Stone": 1},
	"+6 Epheria Galleass: White Wind Sail": {"+5 Epheria Galleass: White Wind Sail": 1, "Frosted Black Stone": 1},
	"+5 Epheria Galleass: White Wind Sail": {"+4 Epheria Galleass: White Wind Sail": 1, "Fiery Black Stone": 1},
	"+4 Epheria Galleass: White Wind Sail": {"+3 Epheria Galleass: White Wind Sail": 1, "Fiery Black Stone": 1},
	"+3 Epheria Galleass: White Wind Sail": {"+2 Epheria Galleass: White Wind Sail": 1, "Fiery Black Stone": 1},
	"+2 Epheria Galleass: White Wind Sail": {"+1 Epheria Galleass: White Wind Sail": 1, "Fiery Black Stone": 1},
	"+1 Epheria Galleass: White Wind Sail": {"Epheria Galleass: White Wind Sail": 1, "Fiery Black Stone": 1},

}
