# a dictionary of item notes

items = {
	"Bartali Sailboat": ["Buy from Proix. 10 mil"],
	"Epheria Sailboat": ["Buy on CM or craft from Bartali Sailboat", "Improved Sailboat works for Caravel"],
	"Epheria Frigate": ["Buy on CM or craft from Bartali Sailboat", "Improved Frigate works for Galleass"],
	"Ship Upgrade Permit: Epheria Sailboat": ["Buy from Falasi. 100 mil."],
	"Ship Upgrade Permit: Epheria Frigate": ["Buy from Falasi. 200 mil."],
	"Ship Upgrade Permit: Epheria Caravel": ["Buy from Falasi. 400 mil."],
	"Ship Upgrade Permit: Epheria Galleass": ["Buy from Falasi. 600 mil."],
	"Verdant Black Stones": ["100 total from Ravinia's quest rewards day 1&4"],
	"Ultimate Armor Reform Stone": ["Buy from CM"],
	"Ultimate Weapon Reform Stone": ["Buy from CM"],
	"Black Stone (Armor)": ["Buy from CM"],

	"Bartali Sailboat: Old Prow": ["Buy from Falasi. 400k."],
	"Bartali Sailboat: Old Plating": ["Buy from Falasi. 500k."],
	"Bartali Sailboat: Old Cannon": ["Buy from Falasi. 400k."],
	"Bartali Sailboat: Old Sail": ["Buy from Falasi. 300k."],

	"Epheria: Old Prow": ["Buy from Falasi. 3.5 mil."],
	"Epheria: Old Plating": ["Buy from Falasi. 4 mil."],
	"Epheria: Old Cannon": ["Buy from Falasi. 3.5 mil."],
	"Epheria: Old Sail": ["Buy from Falasi. 3 mil."],

	"Epheria Caravel: Brass Prow": ["Buy from Falasi. 8 mil."],
	"Epheria Caravel: Upgraded Plating (Green)": ["Buy from Falasi. 9 mil."],
	"Epheria Caravel: Verisha Cannon": ["Buy from Falasi. 8 mil."],
	"Epheria Caravel: White Wind Sail": ["Buy from Falasi. 7 mil."],

	"Epheria Galleass: White Horn Prow": ["Buy from Falasi. 8 mil."],
	"Epheria Galleass: Upgraded Plating (Green)": ["Buy from Falasi. 9 mil."],
	"Epheria Galleass: Verisha Cannon": ["Buy from Falasi. 8 mil."],
	"Epheria Galleass: White Wind Sail": ["Buy from Falasi. 7 mil."],

	"Sea Monster's Ooze": ["Hungry Heraku or Ocean Stalker drop"],
	"Graphite Ingot for Upgrade": ["1x per Heating", "50 total from Ravinia's quest rewards day 1&4"],
	"Timber for Upgrade": ["1x per Chopping", "50 total from Ravinia's quest rewards day 1&4"],
	"Adhesive for Upgrade": ["1x per Heating", "50 total from Ravinia's quest rewards day 1&4"],

	"Zinc Ingot": ["Buy from CM or process"],
	"Old Tree Bark": ["Buy from CM or gather with workers"],
	"Red Tree Lump": ["Buy from CM or gather with workers"],
	"White Cedar Sap": ["Buy from CM or gather with workers"],
	"Acacia Sap": ["Buy from CM or gather with workers"],
	"Elder Tree Sap": ["Buy from CM or gather with workers"],

	"Standardized Timber Square": ["Buy from CM or process"],
	"Steel": ["Buy from CM or process"],
	"Pine Plywood": ["Buy from CM or process"],
	"Flax Fabric": ["Buy from CM or process"],
	"Hard Pillar": ["Buy from CM or process"],
	"Jade Coral Ingot": ["Buy from CM or process"],
	"Pine Coated Plywood": ["Buy from CM or process"],
	"Enhanced Flax Fabric": ["Buy from CM or process"],

	"Khan's Concentrated Magic": ["80,000 Sea Coins"],
	"Luminous Cobalt Ingot": ["800 Sea Coins"],
	"Bright Reef Piece": ["140 Sea Coins", "8x per daily"],
	"Great Ocean Dark Iron": ["160 Sea Coins"],
	"Cobalt Ingot": ["150 Sea Coins"],
	"Brilliant Rock Salt Ingot": ["1,600 Sea Coins"],
	"Seaweed Stalk": ["600 Sea Coins", "4x per daily"],
	"Enhanced Island Tree Coated Plywood": ["80 Sea Coins", "10x per daily"],
	"Cox Pirates' Artifact (Parley Expert)": ["800 Sea Coins", "1x per daily"],
	"Pure Pearl Crystal": ["550 Sea Coins", "2x per daily"],
	"Cox Pirates' Artifact (Parley Beginner)": ["150 Sea Coins"],
	"Deep Sea Memory Filled Glue": ["140 Sea Coins", "8x per daily"],
	"Brilliant Pearl Shard": ["1,600 Sea Coins"],
	"Ruddy Manganese Nodule": ["1,500 Sea Coins", "2x per daily"],
	"Tear of the Ocean": ["3,900 Sea Coins", "1x per daily"],
	"Cox Pirates' Artifact (Combat)": ["800 Sea Coins", "3x per daily"],
	"Khan's Tendon": ["6,000 Sea Coins"],
	"Khan's Scale": ["1,600 Sea Coins"],
	"Frosted Black Stone": ["20 Sea Coins"],
	"Tide-Dyed Standardized Timber Square": ["350 Sea Coins", "3x per daily"],
	"Deep Tide-Dyed Standardized Timber Square": ["1,000 Sea Coins", "3x per daily"],
	"Moon Vein Flax Fabric": ["600 Sea Coins", "3x per daily"],
	"Moon Scale Plywood": ["160 Sea Coins", "10x per daily"],
	"Fiery Black Stone": ["10 Sea Coins"],
	"Mandragora Essence": ["100 Sea Coins"],
}